name: amlec
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26
  - pandas=2.2
  - scipy=1.11
  - matplotlib=3.8
  - statsmodels=0.14
  - seaborn=0.13
  - rpy2=3.5
  - pip
  - pip:
      - tqdm
